language: node_js
sudo: required
node_js:
  - "node"
  - "10"
branch: master
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
script:
  - chmod a+x ./deploy/deploy.sh && ./deploy/deploy.sh
dist: xenial
