language: node_js
sudo: required
node_js:
- node
- '10'
branch: master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_c1ae533aefad_key -iv $encrypted_c1ae533aefad_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'Ryan Lee'
- git config --global user.email 'gxlhybh@gmail.com'
- export TZ='Asia/Shanghai'
script:
- chmod a+x ./deploy/deploy.sh && ./deploy/deploy.sh
dist: xenial
