language: node_js
sudo: required
node_js:
- node
- '10'
branch: master
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name 'Ryan Lee'
- git config --global user.email 'gxlhybh@gmail.com'
- export TZ='Asia/Shanghai'
script:
- chmod a+x ./deploy/deploy.sh && ./deploy/deploy.sh
dist: xenial
